-- Análisis IA de gestiones + follow-ups + alertas in-app (Jhon / James).
-- Aplicar en el SQL Editor del proyecto de cartera (hvtbzxifzkbvmqpshmqw).

create table if not exists public.cartera_gestion_analisis (
  gestion_id bigint primary key references public.cartera_gestiones (id) on delete cascade,
  placa text not null,
  perfil_id text not null references public.cartera_perfiles (id),
  intent text not null
    check (
      intent = any (
        array[
          'compromiso_pago',
          'no_contesta',
          'excusa',
          'agresivo',
          'pagara_otro_dia',
          'otro'
        ]
      )
    ),
  fecha_compromiso timestamptz,
  monto_prometido bigint,
  resumen text,
  confianza real not null default 0,
  analyzed_at timestamptz not null default now(),
  raw_json jsonb
);

create index if not exists cartera_gestion_analisis_placa_idx
  on public.cartera_gestion_analisis (placa, analyzed_at desc);

create index if not exists cartera_gestion_analisis_perfil_idx
  on public.cartera_gestion_analisis (perfil_id, analyzed_at desc);

create table if not exists public.cartera_followups (
  id bigint generated by default as identity primary key,
  placa text not null,
  perfil_id text not null references public.cartera_perfiles (id),
  gestion_id bigint references public.cartera_gestiones (id) on delete set null,
  due_at timestamptz not null,
  motivo text not null,
  status text not null default 'pendiente'
    check (
      status = any (
        array['pendiente', 'disparado', 'cancelado', 'cumplido']
      )
    ),
  created_at timestamptz not null default now()
);

create index if not exists cartera_followups_due_pendiente_idx
  on public.cartera_followups (due_at)
  where status = 'pendiente';

create index if not exists cartera_followups_perfil_idx
  on public.cartera_followups (perfil_id, status, due_at);

create table if not exists public.cartera_alertas (
  id bigint generated by default as identity primary key,
  perfil_id text not null references public.cartera_perfiles (id),
  placa text not null,
  titulo text not null,
  cuerpo text,
  kind text not null
    check (
      kind = any (
        array[
          'compromiso_hoy',
          'compromiso_vencido',
          'rompe_promesa',
          'prioridad'
        ]
      )
    ),
  read_at timestamptz,
  followup_id bigint references public.cartera_followups (id) on delete set null,
  created_at timestamptz not null default now()
);

create index if not exists cartera_alertas_perfil_unread_idx
  on public.cartera_alertas (perfil_id, created_at desc)
  where read_at is null;

create index if not exists cartera_alertas_perfil_idx
  on public.cartera_alertas (perfil_id, created_at desc);

alter table public.cartera_gestion_analisis enable row level security;
alter table public.cartera_followups enable row level security;
alter table public.cartera_alertas enable row level security;

drop policy if exists "cartera_gestion_analisis_all" on public.cartera_gestion_analisis;
create policy "cartera_gestion_analisis_all"
  on public.cartera_gestion_analisis for all
  using (true) with check (true);

drop policy if exists "cartera_followups_all" on public.cartera_followups;
create policy "cartera_followups_all"
  on public.cartera_followups for all
  using (true) with check (true);

drop policy if exists "cartera_alertas_all" on public.cartera_alertas;
create policy "cartera_alertas_all"
  on public.cartera_alertas for all
  using (true) with check (true);

grant select, insert, update, delete on public.cartera_gestion_analisis to anon, authenticated;
grant select, insert, update, delete on public.cartera_followups to anon, authenticated;
grant select, insert, update, delete on public.cartera_alertas to anon, authenticated;

grant usage, select on sequence public.cartera_followups_id_seq to anon, authenticated;
grant usage, select on sequence public.cartera_alertas_id_seq to anon, authenticated;
