-- Lotes fijos 17+ (Jhon Sáenz / James Blanco), plazo 4 días.
-- Aplicar en el SQL Editor del proyecto hvtbzxifzkbvmqpshmqw.

insert into public.cartera_perfiles (id, nombre, activo)
values
  ('jhon_saenz', 'Jhon Sáenz', true),
  ('james_blanco', 'James Blanco', true)
on conflict (id) do update
set
  nombre = excluded.nombre,
  activo = excluded.activo;

create table if not exists public.cartera_lotes_17 (
  id bigint generated by default as identity primary key,
  starts_at timestamptz not null default now(),
  ends_at timestamptz not null,
  status text not null default 'activo'
    check (status = any (array['activo', 'vencido', 'cerrado'])),
  tipo text not null default 'cuotas_17'
    check (tipo = any (array['cuotas_17', 'atraso_3_8'])),
  created_by_perfil_id text references public.cartera_perfiles (id) on delete set null,
  created_at timestamptz not null default now()
);

create table if not exists public.cartera_lote_placas (
  lote_id bigint not null references public.cartera_lotes_17 (id) on delete cascade,
  placa text not null,
  perfil_id text not null references public.cartera_perfiles (id),
  orden integer not null default 0,
  nombre text,
  cedula text,
  deuda_total bigint,
  cuotas_pendientes numeric,
  dias_mora numeric,
  primary key (lote_id, placa)
);

create index if not exists cartera_lotes_17_status_idx
  on public.cartera_lotes_17 (status);

create index if not exists cartera_lote_placas_lote_perfil_idx
  on public.cartera_lote_placas (lote_id, perfil_id);

create index if not exists cartera_lote_placas_placa_idx
  on public.cartera_lote_placas (placa);

alter table public.cartera_lotes_17 enable row level security;
alter table public.cartera_lote_placas enable row level security;

drop policy if exists "cartera_lotes_17_all" on public.cartera_lotes_17;
create policy "cartera_lotes_17_all"
  on public.cartera_lotes_17 for all
  using (true) with check (true);

drop policy if exists "cartera_lote_placas_all" on public.cartera_lote_placas;
create policy "cartera_lote_placas_all"
  on public.cartera_lote_placas for all
  using (true) with check (true);

grant select, insert, update, delete on public.cartera_lotes_17 to anon, authenticated;
grant select, insert, update, delete on public.cartera_lote_placas to anon, authenticated;
grant usage, select on sequence public.cartera_lotes_17_id_seq to anon, authenticated;
