-- Seguimiento de cartera (proyecto Supabase actual de la app).
-- Aplicar en el SQL Editor del proyecto hvtbzxifzkbvmqpshmqw.

create table if not exists public.cartera_perfiles (
  id text primary key,
  nombre text not null,
  activo boolean not null default true
);

create table if not exists public.cartera_casos (
  placa text primary key,
  perfil_id text references public.cartera_perfiles (id) on delete set null,
  categoria text,
  status text not null default 'pendiente'
    check (
      status = any (
        array[
          'pendiente',
          'contactado',
          'compromiso',
          'abono',
          'no_contesta',
          'visita',
          'en_ruta',
          'recuperada',
          'cerrado'
        ]
      )
    ),
  notas text,
  updated_at timestamptz not null default now()
);

create table if not exists public.cartera_gestiones (
  id bigint generated by default as identity primary key,
  placa text not null,
  perfil_id text not null references public.cartera_perfiles (id),
  status text not null,
  categoria text,
  notas text,
  monto bigint,
  created_at timestamptz not null default now()
);

create index if not exists cartera_gestiones_placa_created_idx
  on public.cartera_gestiones (placa, created_at desc);

insert into public.cartera_perfiles (id, nombre, activo)
values
  ('jhon_saenz', 'Jhon Sáenz', true),
  ('dayana', 'Dayana', true),
  ('santiago_saenz', 'Santiago Sáenz', true),
  ('angie_garcia', 'Angie García', true),
  ('mauricio_perucho', 'Mauricio Perucho', true)
on conflict (id) do update
set
  nombre = excluded.nombre,
  activo = excluded.activo;

-- Acceso desde la app (mismo patrón permisivo que placas/recuperadores).
alter table public.cartera_perfiles enable row level security;
alter table public.cartera_casos enable row level security;
alter table public.cartera_gestiones enable row level security;

drop policy if exists "cartera_perfiles_all" on public.cartera_perfiles;
create policy "cartera_perfiles_all"
  on public.cartera_perfiles for all
  using (true) with check (true);

drop policy if exists "cartera_casos_all" on public.cartera_casos;
create policy "cartera_casos_all"
  on public.cartera_casos for all
  using (true) with check (true);

drop policy if exists "cartera_gestiones_all" on public.cartera_gestiones;
create policy "cartera_gestiones_all"
  on public.cartera_gestiones for all
  using (true) with check (true);

grant select, insert, update, delete on public.cartera_perfiles to anon, authenticated;
grant select, insert, update, delete on public.cartera_casos to anon, authenticated;
grant select, insert, update, delete on public.cartera_gestiones to anon, authenticated;
grant usage, select on sequence public.cartera_gestiones_id_seq to anon, authenticated;
